// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export const Category = {
    MOVIES: 'movies',
    MUSIC: 'music',
    BOOKS: 'books',
    ART: 'art'
} as const;

export type Category = typeof Category[keyof typeof Category];

export const CatalogItemType = { MEDIA: 'media', PERSON: 'person' } as const;

export type CatalogItemType = typeof CatalogItemType[keyof typeof CatalogItemType];

export const Segment = {
    INSTINCTS: 'instincts',
    INTELLECT: 'intellect',
    BALANCE: 'balance'
} as const;

export type Segment = typeof Segment[keyof typeof Segment];

export const Topic = {
    AESTHETICS: 'aesthetics',
    SELF_EXPRESSION: 'self-expression',
    LIVE: 'live',
    DOCUMENTARY: 'documentary',
    SERIES: 'series'
} as const;

export type Topic = typeof Topic[keyof typeof Topic];

export const Mode = { WORKS: 'works', CREATORS: 'creators' } as const;

export type Mode = typeof Mode[keyof typeof Mode];

export const MovieKind = { MOVIE: 'movie' } as const;

export type MovieKind = typeof MovieKind[keyof typeof MovieKind];

export const DirectorKind = { DIRECTOR: 'director' } as const;

export type DirectorKind = typeof DirectorKind[keyof typeof DirectorKind];

export const MovieMetaType = { MOVIE_META: 'movie_meta' } as const;

export type MovieMetaType = typeof MovieMetaType[keyof typeof MovieMetaType];

export const ContributorMetaType = { DIRECTOR_META: 'director_meta', WRITER_META: 'writer_meta' } as const;

export type ContributorMetaType = typeof ContributorMetaType[keyof typeof ContributorMetaType];

export type CatalogResponse = {
    meta: PaginationMeta;
    items: Array<CatalogItem>;
};

export type BaseCatalogItem = {
    id: string;
    title: string;
    subtitle: string;
    coverUrl: string;
    category: Category;
    type: CatalogItemType;
    currentSegment: Segment | null;
    currentTopic: Topic | null;
};

export type CatalogItem = ({
    kind: 'movie';
} & CatalogMovieItem) | ({
    kind: 'director';
} & CatalogDirectorItem);

export type CatalogMovieItem = BaseCatalogItem & {
    kind: MovieKind;
    type: 'media';
    metadata: CatalogMovieMeta;
};

export type CatalogDirectorItem = BaseCatalogItem & {
    kind: DirectorKind;
    type: 'person';
    metadata: CatalogContributorMeta;
};

export type CatalogMovieMeta = {
    id: string;
    metaType: MovieMetaType;
    slug: string;
    mediaUrl: string;
    posters: Array<string>;
    runtime: number;
};

export type CatalogContributorMeta = {
    id: string;
    metaType: ContributorMetaType;
    slug: string;
};

export type Movie = {
    id: string;
    title: string;
    slug: string;
    posters: Array<string>;
    runtime: number;
    createdAt: string;
    updatedAt: string;
    segment: Segment | null;
    topic: Topic | null;
};

export type PaginationMeta = {
    currentPage: number;
    perPage: number;
    hasNextPage: boolean;
    hasPrevPage: boolean;
    total: number;
    totalPages: number;
};

export type Error = {
    statusCode: number;
    message: string;
    error: string;
};

export type PageParam = number;

export type LimitParam = number;

export type GetCatalogData = {
    body?: never;
    path: {
        category: Category;
    };
    query?: {
        segment?: Segment;
        topic?: Topic;
        mode?: Mode;
        page?: number;
        limit?: number;
    };
    url: '/catalog/{category}';
};

export type GetCatalogErrors = {
    /**
     * Bad Request
     */
    400: Error;
};

export type GetCatalogError = GetCatalogErrors[keyof GetCatalogErrors];

export type GetCatalogResponses = {
    /**
     * Success
     */
    200: CatalogResponse;
};

export type GetCatalogResponse = GetCatalogResponses[keyof GetCatalogResponses];

export type GetMovieByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/movies/{id}';
};

export type GetMovieByIdErrors = {
    /**
     * Not found
     */
    404: Error;
};

export type GetMovieByIdError = GetMovieByIdErrors[keyof GetMovieByIdErrors];

export type GetMovieByIdResponses = {
    /**
     * Found
     */
    200: Movie;
};

export type GetMovieByIdResponse = GetMovieByIdResponses[keyof GetMovieByIdResponses];
