/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get content list (Catalog View)
         * @description Returns a list of items with polymorphic metadata for filtering and preview.
         */
        get: {
            parameters: {
                query?: {
                    segment?: components["schemas"]["Segment"];
                    topic?: components["schemas"]["Topic"];
                    mode?: "works" | "creators";
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    category: "movies" | "music" | "books" | "art";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get movie details (Detail View)
         * @description Returns full details of a specific movie. No polymorphic metadata here.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Movie details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Movie"];
                    };
                };
                /** @description Movie not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogResponse: {
            meta: components["schemas"]["PaginationMeta"];
            items: components["schemas"]["CatalogItem"][];
        };
        /** @description Represents a preview item in the catalog list. */
        CatalogItem: {
            /** Format: uuid */
            id: string;
            title: string;
            subtitle?: string;
            /** Format: uri */
            coverUrl?: string;
            kind: components["schemas"]["ItemKind"];
            currenSegment?: components["schemas"]["Segment"];
            currentTopic?: components["schemas"]["Topic"];
            /** @description Lightweight specific data for preview cards. */
            metadata?: components["schemas"]["CatalogMovieMeta"] | null;
        };
        CatalogMovieMeta: {
            id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            metaType: "movie_meta";
            /** @description url */
            mediaUrl?: string;
            slug?: string;
        };
        /** @description Full detail object for a Movie. NO 'metadata' field wrapper. */
        Movie: {
            /** Format: uuid */
            id: string;
            title: string;
            subTitle?: string;
            slug: string;
            /** @description Full synopsis of the movie */
            description?: string;
            /** Format: uri */
            coverUrl?: string;
            /**
             * Format: uri
             * @description Direct link to the stream/file
             */
            mediaUrl?: string;
            duration?: number;
            /** Format: date */
            releaseDate?: string;
            director?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
            segment?: components["schemas"]["Segment"];
            topic?: components["schemas"]["Topic"];
        };
        PaginationMeta: {
            currentPage?: number;
            perPage?: number;
            total?: number;
            totalPages?: number;
        };
        /** @enum {string} */
        ItemKind: "movie" | "movie_creator" | "book" | "book_creator" | "music" | "music_creator" | "art" | "art_creator";
        /** @enum {string} */
        Segment: "instincts" | "intellect" | "balance";
        /** @enum {string} */
        Topic: "aesthetics" | "self-expression" | "live" | "documentary" | "series";
        Error: {
            code?: number;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
