openapi: 3.0.3
info:
  title: Content Aggregator API
  version: 1.0.7
  description: API for a content aggregator covering Movies, Music, Books, and Art.

servers:
  - url: /api/v1
    description: Production Server

paths:
  /catalog/{category}:
    get:
      summary: Get content list (Catalog View)
      operationId: getCatalog
      tags:
        - Catalog
      parameters:
        - name: category
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Category'
        - name: segment
          in: query
          schema:
            $ref: '#/components/schemas/Segment'
        - name: topic
          in: query
          schema:
            $ref: '#/components/schemas/Topic'
        - name: mode
          in: query
          schema:
            $ref: '#/components/schemas/Mode'
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/LimitParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /movies/{id}:
    get:
      summary: Get movie details
      operationId: getMovieById
      tags:
        - Movies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    PageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 1
    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 20

  schemas:
    # --- GLOBAL ENUMS ---
    Category:
      type: string
      enum: ['movies', 'music', 'books', 'art']

    # New enum for high-level grouping in UI
    CatalogItemType:
      type: string
      enum: ['media', 'person']

    Segment:
      type: string
      enum: ['instincts', 'intellect', 'balance']

    Topic:
      type: string
      enum: ['aesthetics', 'self-expression', 'live', 'documentary', 'series']

    Mode:
      type: string
      enum: ['works', 'creators']

    # --- SPECIFIC ENUMS ---
    
    MovieKind:
      type: string
      enum: ['movie']

    DirectorKind:
      type: string
      enum: ['director']

    MovieMetaType:
      type: string
      enum: ['movie_meta']

    ContributorMetaType:
      type: string
      enum: ['director_meta', 'writer_meta']

    # --- RESPONSES ---

    CatalogResponse:
      type: object
      additionalProperties: false
      required:
        - meta
        - items
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        items:
          type: array
          items:
            $ref: '#/components/schemas/CatalogItem'

    BaseCatalogItem:
      type: object
      additionalProperties: false
      required:
        - id
        - title
        - subtitle
        - coverUrl
        - category       # New required field
        - type           # New required field
        - currentSegment
        - currentTopic
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        subtitle:
          type: string
        coverUrl:
          type: string
          format: uri
        category:
          $ref: '#/components/schemas/Category'
        type:
          $ref: '#/components/schemas/CatalogItemType'
        currentSegment:
          allOf:
            - $ref: '#/components/schemas/Segment'
          nullable: true
        currentTopic:
          allOf:
            - $ref: '#/components/schemas/Topic'
          nullable: true

    CatalogItem:
      oneOf:
        - $ref: '#/components/schemas/CatalogMovieItem'
        - $ref: '#/components/schemas/CatalogDirectorItem'
      discriminator:
        propertyName: kind
        mapping:
          movie: '#/components/schemas/CatalogMovieItem'
          director: '#/components/schemas/CatalogDirectorItem'

    CatalogMovieItem:
      allOf:
        - $ref: '#/components/schemas/BaseCatalogItem'
        - type: object
          additionalProperties: false
          required:
            - kind
            - type
            - metadata
          properties:
            kind:
              $ref: '#/components/schemas/MovieKind'
            
            # Narrowing: Movie is ALWAYS media
            type:
              type: string
              enum: ['media']
              
            metadata:
              $ref: '#/components/schemas/CatalogMovieMeta'

    CatalogDirectorItem:
      allOf:
        - $ref: '#/components/schemas/BaseCatalogItem'
        - type: object
          additionalProperties: false
          required:
            - kind
            - type
            - metadata
          properties:
            kind:
              $ref: '#/components/schemas/DirectorKind'
            
            # Narrowing: Director is ALWAYS person
            type:
              type: string
              enum: ['person']
              
            metadata:
              $ref: '#/components/schemas/CatalogContributorMeta'

    CatalogMovieMeta:
      type: object
      additionalProperties: false
      required:
        - metaType
        - id
        - slug
        - mediaUrl
        - posters
        - runtime
      properties:
        id:
          type: string
          format: uuid
        metaType:
          $ref: '#/components/schemas/MovieMetaType'
        slug: 
          type: string
        mediaUrl:
          type: string
        posters:
          type: array
          items:
            type: string
        runtime: 
          type: integer

    CatalogContributorMeta:
      type: object
      additionalProperties: false
      required:
        - metaType
        - id
        - slug
      properties:
        id:
          type: string
          format: uuid
        metaType:
          $ref: '#/components/schemas/ContributorMetaType'
        slug:
          type: string

    Movie:
      type: object
      additionalProperties: false
      required:
        - id
        - title
        - slug
        - posters
        - runtime
        - createdAt
        - updatedAt
        - segment
        - topic
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        posters:
          type: array
          items:
            type: string
        runtime:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        segment:
          allOf:
            - $ref: '#/components/schemas/Segment'
          nullable: true
        topic:
          allOf:
            - $ref: '#/components/schemas/Topic'
          nullable: true

    PaginationMeta:
      type: object
      additionalProperties: false
      required:
        - currentPage
        - perPage
        - hasNextPage
        - hasPrevPage
        - total
        - totalPages
      properties:
        currentPage:
          type: integer
        perPage:
          type: integer
        hasNextPage:
          type: boolean
        hasPrevPage:
          type: boolean
        total:
          type: integer
        totalPages:
          type: integer

    Error:
      type: object
      additionalProperties: false
      required:
        - statusCode
        - message
        - error
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string