import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProviders } from "./app-providers";

const Arial = localFont({
  src: [
    {
      path: "../../public/fonts/arial-bold.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/arial-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/arial-regular.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-arial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${Arial.className} antialiased`}>
          <AppProviders>
            {children}
          </AppProviders>
      </body>
    </html>
  );
}
