// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, useInfiniteQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCatalog, getMovieById, type Options } from '../sdk.gen';
import type { GetCatalogData, GetCatalogError, GetCatalogResponse, GetMovieByIdData, GetMovieByIdError, GetMovieByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCatalogQueryKey = (options: Options<GetCatalogData>) => createQueryKey('getCatalog', options);

/**
 * Get content list (Catalog View)
 */
export const getCatalogOptions = (options: Options<GetCatalogData>) => queryOptions<GetCatalogResponse, GetCatalogError, GetCatalogResponse, ReturnType<typeof getCatalogQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCatalog({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCatalogQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getCatalogInfiniteQueryKey = (options: Options<GetCatalogData>): QueryKey<Options<GetCatalogData>> => createQueryKey('getCatalog', options, true);

/**
 * Get content list (Catalog View)
 */
export const getCatalogInfiniteOptions = (options: Options<GetCatalogData>) => infiniteQueryOptions<GetCatalogResponse, GetCatalogError, InfiniteData<GetCatalogResponse>, QueryKey<Options<GetCatalogData>>, number | Pick<QueryKey<Options<GetCatalogData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCatalogData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCatalog({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCatalogInfiniteQueryKey(options)
});

export const getMovieByIdQueryKey = (options: Options<GetMovieByIdData>) => createQueryKey('getMovieById', options);

/**
 * Get movie details
 */
export const getMovieByIdOptions = (options: Options<GetMovieByIdData>) => queryOptions<GetMovieByIdResponse, GetMovieByIdError, GetMovieByIdResponse, ReturnType<typeof getMovieByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMovieById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMovieByIdQueryKey(options)
});
